### ISSUE TITLE
Create abstraction project

### ISSUE THREAD

**Issue by Meir017** [kblok/playwright-sharp#1]
This should include all interfaces and classes without specific implementation

I was thinking of `Playwright.Abstractions` and then `Playwright` would be the project including all of the browsers

tasks:

- [ ] `src/accessibility.ts`
- [ ] `src/browser.ts`
- [ ] `src/browserContext.ts`
- [ ] `src/console.ts`
- [ ] `src/deviceDescriptors.ts`
- [ ] `src/dialog.ts`
- [ ] `src/dom.ts`
- [ ] `src/frames.ts`
- [ ] `src/input.ts`
- [ ] `src/javascript.ts`
- [ ] `src/network.ts`
- [ ] `src/page.ts`
- [ ] `src/screenshotter.ts`
- [ ] `src/timeoutSettings.ts`
- [ ] `src/transport.ts`
- [ ] `src/types.ts`
- [ ] `src/usKeyboardLayout.ts`
- [ ] `src/server/browserFetcher.ts`
- [ ] `src/server/processLauncher.ts`

**Comment by kblok** [comment]
We'll get there, patience :) I'm working on some project planning.
I want to start better this time, build some scaffolding and then let **tests** be our implementation guide.
