### ISSUE TITLE
First scafolding

### ISSUE THREAD

**Issue by kblok** [kblok/playwright-sharp#2]
We need to build the first structure to start working

**Comment by Meir017** [comment]
@kblok seems to me that the naming of the projects isn't consistant
- Playwright.Chromium
- Playwright.Firefox
- Playwright.Webkit
- PlaywrightSharp
- PlaywrightSharp.Abstractions
- PlaywrightSharp.Tests

shouldn't the browser specific projects be prefixed with `PlaywrightSharp` too?

**Comment by kblok** [comment]
@Meir017 so glad to see your eagle eyes again :)
